### ISSUE TITLE
A survey submission should be associated with the admin who created it 

### ISSUE THREAD

**Issue by Dev1000** [Dev1000/orion#1]
**Description**
In the cases where an admin is signed in when they take a survey, we would like to know that.

**Tasks**
- [ ] Setup an association between the SurveySubmission and Admin models so that we know which survey submissions were submitted by which admin.
- [ ] If an admin is signed in, ensure that the survey submission is associated with them.
- [ ] Display the admin's name in the Survey Submissions index next to their submission. If there is no admin associated with it, display "Anonymous."

**Comment by Dev1000** [comment]
The Add Questions doesn't work in Firefox 47.0

**Comment by Dev1000** [comment]
rails generate migration add_admin_id_to_survey_submissions admin_id:integer
